### ISSUE TITLE
Can we load model from local with out internet?

### ISSUE THREAD

**Issue by sd-OFF** [isl-org/ZoeDepth#9]
I wanted to load from local but buildmodel function in zeodepth needs internet for getting state_dict. Do you have similar local  load_model function like midas.model_loader.load_model

**Comment by shariqfarooq123** [comment]
Yes, you can provide `pretrained_resource="local::/path/to/checkpoint.pt"` to the config for build_model function like so:

```python
from zoedepth.models.builder import build_model
from zoedepth.utils.config import get_config

# ZoeD_N
conf = get_config("zoedepth", "infer", pretrained_resource="local::/path/to/checkpoint.pt")
model_zoe_n = build_model(conf)
```

where `local::` prefix indicates checkpoint is present locally on disk. See https://github.com/isl-org/ZoeDepth/blob/2361c75ea8df1e75ea2feebef7c56a96400f1c6a/zoedepth/models/model_io.py#L64 for details.

Note: loading from torch hub caches the checkpoint so that model file is downloaded only once (first use).
